<?php
  $labels['category'] = 'Category';
  $labels['loadcategory'] = 'Load category ... ';
  $labels['loadlist'] = 'Load Passwords ...';
  $labels['loading'] = 'Loading ...';
  $labels['nok'] = 'NOK';
  $labels['notconfigured'] = 'Not configured';
  $labels['ok'] = 'OK';
  $labels['serverconnection'] = 'Connection to server';
  $labels['nextcloud_passwords_settings'] = 'Nextcloud Passwords Settings';
  $labels['passwords'] = 'Passwords';
?>