<?php
  $labels['category'] = 'Catégorie';
  $labels['loadcategory'] = 'Chargement des catégories ... ';
  $labels['loadlist'] = 'Récupération des mot de passe ...';
  $labels['loading'] = 'Chargement ...';
  $labels['nok'] = 'NOK';
  $labels['notconfigured'] = 'Non configuré';
  $labels['ok'] = 'OK';
  $labels['serverconnection'] = 'Connection au serveur';
  $labels['nextcloud_passwords_settings'] = 'Paramètres des mot de passe NextCloud';
  $labels['passwords'] = 'Mot de passe';
?>